In [1]:
#Welcome to Numpy 

In [2]:
#NUMPY - NUMERICAL PYTHON 
#STANDARD PYTHON LIBRARY FOR SCIENTIFIC AND NUMERICAL COMPUTING  

In [3]:
#FEATURES 
#NUMPY ARRAYS - 2 main types or flavors 
# vectors, these are 1-d arrays 
# arrays, these are 2-d arrays 

In [4]:
import numpy

In [5]:
#create a list 
l1 = [1,4,8,12]
ar2 = numpy.array(l1)

In [6]:
#1-d array 
ar2

array([ 1,  4,  8, 12])

In [7]:
#2d array 
l2 = [[1,4,8,12], [1,2,3,4]]

In [8]:
ar2 = numpy.array(l2)

In [9]:
ar2

array([[ 1,  4,  8, 12],
       [ 1,  2,  3,  4]])

In [10]:
#properties of 2-d 
#on viewing, notice the 2 square brackets 


In [11]:
#simplify your imports by renaming 
import numpy as np 

In [13]:
np.arange(0, 10) #creates an array with the range specified -1 


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#optional 3 arg, for the STEP SIZE  

np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
#other arrays you can create are:
# array of zeros
# array of ones  

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
#creating a 2-d array with ones 

np.ones((3,4)) #3rows, 4values each

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
#create other arrays using linspace method
# np.linspace(lower_bound, upper_bound,no_of_values)

In [20]:
np.linspace(1,11,100)

array([ 1.        ,  1.1010101 ,  1.2020202 ,  1.3030303 ,  1.4040404 ,
        1.50505051,  1.60606061,  1.70707071,  1.80808081,  1.90909091,
        2.01010101,  2.11111111,  2.21212121,  2.31313131,  2.41414141,
        2.51515152,  2.61616162,  2.71717172,  2.81818182,  2.91919192,
        3.02020202,  3.12121212,  3.22222222,  3.32323232,  3.42424242,
        3.52525253,  3.62626263,  3.72727273,  3.82828283,  3.92929293,
        4.03030303,  4.13131313,  4.23232323,  4.33333333,  4.43434343,
        4.53535354,  4.63636364,  4.73737374,  4.83838384,  4.93939394,
        5.04040404,  5.14141414,  5.24242424,  5.34343434,  5.44444444,
        5.54545455,  5.64646465,  5.74747475,  5.84848485,  5.94949495,
        6.05050505,  6.15151515,  6.25252525,  6.35353535,  6.45454545,
        6.55555556,  6.65656566,  6.75757576,  6.85858586,  6.95959596,
        7.06060606,  7.16161616,  7.26262626,  7.36363636,  7.46464646,
        7.56565657,  7.66666667,  7.76767677,  7.86868687,  7.96

In [21]:
#Question 
#Is the array generated above 1-d or 2-d ?
# Answer = 1-d (only 1 square bracket)

In [22]:
#check the type of array using the shape method 
ar3 = np.linspace(1,11,100)
ar3.shape

(100,)

In [23]:
#Check shape of ar2 (2-d)
ar2.shape

(2, 4)

In [24]:
#check datatypes using the dtype() method 

In [25]:
print(ar2.dtype)

int32


In [26]:
print(ar3.dtype)

float64


In [30]:
#find the max and min values in an array using the 
# max and min functns

ar2.min()

1

In [29]:
ar3.max()

11.0

In [32]:
#find the position using argmax or argmin
# 
# ar3.argmax()
ar3.argmax() 
ar3.argmin()

0

In [33]:
#Generating random values (btw 0 and 1)
rd1 = np.random.rand(3)

In [34]:
print(rd1) #generates 3 random values btw 0 and 1 as a single 1-d array 

[0.46536436 0.84524526 0.35491699]


In [35]:
rd2 = np.random.rand(3,3)
print(rd2) #generates a 2-d array with 3 random values / 3 rows 

[[0.02964978 0.38375028 0.46356677]
 [0.72018331 0.65555406 0.6392894 ]
 [0.93185659 0.54488671 0.75294134]]


In [36]:
#create a random, normal distribution 
rd3 = np.random.randn(3,3)
print(rd3)

[[ 0.60555748 -1.49086657  0.07788612]
 [ 0.04974282  0.98877465  0.53039738]
 [ 0.23530422  0.69039892  1.87203366]]


In [37]:
#create a random, normal distribution 
rd4 = np.random.randint(1,100,10) #starting/ base value, max value, no_of_total values 
print(rd4)

[97 86 21 13 89 57 20 83  7 85]


In [38]:
#Manipulating arrays 
#Example 
ar4 = np.arange(5,101,5)

In [39]:
ar4 
#result is a 1-d array with 20 values 
#this is a vector 

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [40]:
ar4.reshape(5,4)
#reshape to a 2-d array with same 20 values 
# rows 5, values per row 4 
# this is a matrix

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [ 65,  70,  75,  80],
       [ 85,  90,  95, 100]])

In [41]:
#Use the shape method to confirm 
ar4.shape

(20,)

In [42]:
ar4b = ar4.reshape(5,4)

In [43]:
ar4b.size

20

In [44]:
ar4b.shape

(5, 4)

In [45]:
#slicing 
#index numbering is key 
ar4b[1:3,2:4]

array([[35, 40],
       [55, 60]])

In [46]:
#1:3 signifies rows 
#sliced from the 1 row to the 3rd row, 3 excluded so just row 1 and 2.import
#Note rows start from zero, 0 

In [47]:
#2:4 signifies cols
#sliced from col 2 to 4, col 4 excluded so just 2 and 3. 
#Cols also start from index 0


In [48]:
#more slicing 
ar4b[3,:] #returns the entire 4th row 

array([65, 70, 75, 80])

In [49]:
arrslice = ar4b[3,:] #holds sam values and structure 

In [52]:
#change values by:
arrslice[:] = 100
arrslice

array([100, 100, 100, 100])

In [53]:
#this action will change the original array as it is not a true copy 
ar4b

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [100, 100, 100, 100],
       [ 85,  90,  95, 100]])

In [63]:
#Make a true copy 
ar4c = ar4.reshape(5,4)
arrcopy = ar4c.copy() #true copy 

In [64]:
#test the copied arrays
arrcopy


array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [100, 100, 100, 100],
       [ 85,  90,  95, 100]])

In [65]:
arrcopy[:] = 100

In [66]:
arrcopy

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [67]:
ar4

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60, 100,
       100, 100, 100,  85,  90,  95, 100])

In [68]:
#comparison operators 
ar4 > 50

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [70]:
#create 2 arrays and test arithmetic operations 
arr1 = np.arange(0,11)
arr2 = np.arange(0,21,2)

In [72]:
#check the size to make sure they are same 
arr2.size

11

In [73]:
arr1 + arr2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [74]:

arr1 * arr2

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162, 200])

In [75]:
arr1 - arr2

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10])

In [76]:
arr1/arr2

array([nan, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

ZeroDivisionError: division by zero