In [2]:
import numpy as np

In [5]:
array1 = np.random.randint(2,100,50)

In [6]:
array2 = np.random.randint(2,100,50)

In [7]:
array1

array([26, 12, 68, 14, 60, 14, 41, 58, 71, 12, 88, 59, 51, 39, 18, 34,  3,
       31, 42, 91, 68, 22,  5, 24,  9, 58, 45, 35, 15, 10, 19, 64, 58, 95,
       63, 43, 59, 51, 16, 40, 97, 81, 79, 37, 53, 41, 56, 53, 62, 33])

In [8]:
array2

array([24,  3, 11, 68, 53, 88,  8, 54, 21,  9, 31, 13, 78, 46, 47, 21, 17,
        3, 77, 13,  7, 75, 21, 87, 67,  7, 49, 67, 59, 85, 58, 63, 64, 14,
       22, 20, 74,  4, 39, 80,  5, 37,  7, 37, 32,  4, 29, 93, 59, 10])

In [9]:
array3 = np.random.rand(2,100,50)

In [10]:
array3

array([[[0.3682026 , 0.79719176, 0.64689257, ..., 0.56741729,
         0.08634203, 0.74656097],
        [0.5250864 , 0.83133988, 0.63062162, ..., 0.72023117,
         0.92142266, 0.69631516],
        [0.09921969, 0.86861858, 0.15463493, ..., 0.05161438,
         0.93834926, 0.20073982],
        ...,
        [0.73684005, 0.31779009, 0.67992435, ..., 0.44247225,
         0.92103465, 0.49382589],
        [0.83459719, 0.54589655, 0.46382699, ..., 0.65467166,
         0.15826557, 0.59717912],
        [0.18231447, 0.922312  , 0.52810433, ..., 0.00708169,
         0.57941592, 0.28368815]],

       [[0.64340907, 0.89934087, 0.33692873, ..., 0.07979271,
         0.83974227, 0.77017204],
        [0.60955393, 0.16449568, 0.64522638, ..., 0.45247798,
         0.46219903, 0.22735005],
        [0.73830117, 0.29809896, 0.30275522, ..., 0.04136448,
         0.9530868 , 0.68801617],
        ...,
        [0.77586171, 0.06983148, 0.51437022, ..., 0.4336812 ,
         0.23523522, 0.88285526],
        [0.8

In [18]:
arr = np.array([2,3,4,5,6,])

In [19]:
arr

array([2, 3, 4, 5, 6])

In [20]:
arr2 = np.array((1,2,3,4,5,6,7))

In [21]:
arr2

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
#0-D Arrays
arr3 = np.array(45)
arr3

array(45)

In [25]:
#1-D Arrays
arr4 = np.array([1,2,3,4,5])

print(arr4)

arr4

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [27]:
#2-D Arrays

arr = np.array([[1,2,3],[4,5,6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
#3-D Arrays
arr = np.array([[[1,2,3], [4,5,6],[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


In [37]:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [38]:
arr = np.array([1,2,3,4], ndmin=5)

print (arr)

print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [40]:
#Access Array Elements

arr = np.array([1,2,3,4])

print(arr[0])

1


In [41]:
arr = np.array([1,2,3,4])
print(arr[1])

2


In [42]:
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

7


In [44]:
#Access 2-D Arrays

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('2nd element on 1st dim: ',arr[0,1])

2nd element on 1st dim:  2


In [45]:
print('5th element on the 2nd dim: ', arr[1,4])

5th element on the 2nd dim:  10


In [47]:
#Access 3-D Arrays

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [48]:
#Negative Indexing
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1,-1])

Last element from 2nd dim:  10


In [49]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [50]:
print(arr[4:])

[5 6 7]


In [51]:
#steps in array slicing 

print(arr[1:5:2])


[2 4]


In [52]:
print(arr[::2])

[1 3 5 7]


In [53]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1[1, 1:4])

[7 8 9]


In [54]:
print(arr1[0:2, 2])

[3 8]


In [55]:
print(arr1[0:2, 1:4]) #slice index 1 to index 4, from both elements. 

[[2 3 4]
 [7 8 9]]
