In [2]:
#Numpy 
#What is the difference btw a python list and a Numpy Array ?
"""NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous."""

"""NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.
"""

'NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.\n'

In [4]:
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [5]:
#sort numbers in ascending order using 
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
'''
In addition to sort, which returns a sorted copy of an array, you can use:

argsort, which is an indirect sort along a specified axis,

lexsort, which is an indirect stable sort on multiple keys,

searchsorted, which will find elements in a sorted array, and

partition, which is a partial sort.
'''

'\nIn addition to sort, which returns a sorted copy of an array, you can use:\n\nargsort, which is an indirect sort along a specified axis,\n\nlexsort, which is an indirect stable sort on multiple keys,\n\nsearchsorted, which will find elements in a sorted array, and\n\npartition, which is a partial sort.\n'

In [7]:
#concatenate two arrays with...
#You can concatenate them with np.concatenate().
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [8]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
#Type 2
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [16]:
np.concatenate((x, y), axis=0) #will still run without the axis 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Indexing and Slicing Arrays 
